title: Ian McMeeking # your name (or website title) here
logo: "/images/McMeeking-Picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  STEM Educator and Curriculum Writer 
  <br><br>
  Number and Data Enthusiast 
  <br><br>
  <a href="https://www.linkedin.com/in/ianmcmeeking/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
